// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxL-k9gt0vq5FimuhIf3ZJHcpC3AJTEtI',
    appId: '1:246853441241:web:858ec13811663c8e0ad0c8',
    messagingSenderId: '246853441241',
    projectId: 'wydatki-c72f3',
    authDomain: 'wydatki-c72f3.firebaseapp.com',
    storageBucket: 'wydatki-c72f3.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA74nvJb9J1hBFrTMINgNIqGBKncSYot5Q',
    appId: '1:246853441241:android:5a2c1d4a20f7d4970ad0c8',
    messagingSenderId: '246853441241',
    projectId: 'wydatki-c72f3',
    storageBucket: 'wydatki-c72f3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAT7c0nPVWf3TabNcLC3lsNWooESZmynMk',
    appId: '1:246853441241:ios:27e9619569c6a0030ad0c8',
    messagingSenderId: '246853441241',
    projectId: 'wydatki-c72f3',
    storageBucket: 'wydatki-c72f3.appspot.com',
    iosClientId: '246853441241-86o5t78vc8dh2udo4cqsbdo9falc1lnq.apps.googleusercontent.com',
    iosBundleId: 'com.marcinplinta.wydatki',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAT7c0nPVWf3TabNcLC3lsNWooESZmynMk',
    appId: '1:246853441241:ios:27e9619569c6a0030ad0c8',
    messagingSenderId: '246853441241',
    projectId: 'wydatki-c72f3',
    storageBucket: 'wydatki-c72f3.appspot.com',
    iosClientId: '246853441241-86o5t78vc8dh2udo4cqsbdo9falc1lnq.apps.googleusercontent.com',
    iosBundleId: 'com.marcinplinta.wydatki',
  );
}
